# Identificación del proyecto en SonarQube
sonar.projectKey=backend-flask-python
sonar.projectName=Backend Flask Python
sonar.projectVersion=1.0

# URL de tu servidor SonarQube
sonar.host.url=http://localhost:9000

# (Opcional) Si tu SonarQube requiere autenticación, descomenta esta línea y pon tu token
sonar.login=sqp_95b14b680fc5d3a481ef91fe8b4029d4d63f1cea

# Directorio donde está tu código
sonar.sources=.

# Codificación
sonar.sourceEncoding=UTF-8

# Lenguaje del proyecto
sonar.language=py

# Archivo de reporte de cobertura
sonar.python.coverage.reportPaths=coverage.xml

# Exclusiones (cosas que no quieres analizar)
sonar.exclusions=**/venv/**,**/__pycache__/**,**/tests/**